import pandas as pd

df = pd.read_csv('first.csv')

#dnp
df = df.drop(columns=['COMMENT','RECENT_SEASON_ID', 'RECENT_Game_ID','RECENT_GAME_DATE', 'RECENT_MATCHUP', 'RECENT_WL'  ])
df = df.dropna(how="any")


#SEASON
df['SEASON_MIN'] = df['SEASON_MIN']/df['SEASON_GP']
df['SEASON_FGM'] = df['SEASON_FGM']/df['SEASON_GP']
df['SEASON_FGA'] = df['SEASON_FGA']/df['SEASON_GP']
df['SEASON_FG3M'] = df['SEASON_FG3M']/df['SEASON_GP']
df['SEASON_FG3A'] = df['SEASON_FG3A']/df['SEASON_GP']
df['SEASON_FTM'] = df['SEASON_FTM']/df['SEASON_GP']
df['SEASON_FTA'] = df['SEASON_FTA']/df['SEASON_GP']
df['SEASON_OREB'] = df['SEASON_OREB']/df['SEASON_GP']
df['SEASON_DREB'] = df['SEASON_DREB']/df['SEASON_GP']
df['SEASON_REB'] = df['SEASON_REB']/df['SEASON_GP']
df['SEASON_AST'] = df['SEASON_AST']/df['SEASON_GP']
df['SEASON_STL'] = df['SEASON_STL']/df['SEASON_GP']
df['SEASON_BLK'] = df['SEASON_BLK']/df['SEASON_GP']
df['SEASON_TOV'] = df['SEASON_TOV']/df['SEASON_GP']
df['SEASON_PF'] = df['SEASON_PF']/df['SEASON_GP']
df['SEASON_PTS'] = df['SEASON_PTS']/df['SEASON_GP']

#recent

#team
df['TEAM_MIN'] = df['TEAM_MIN']/df['TEAM_GP']
df['TEAM_FGM'] = df['TEAM_FGM']/df['TEAM_GP']
df['TEAM_FGA'] = df['TEAM_FGA']/df['TEAM_GP']
df['TEAM_FG3M'] = df['TEAM_FG3M']/df['TEAM_GP']
df['TEAM_FG3A'] = df['TEAM_FG3A']/df['TEAM_GP']
df['TEAM_FTM'] = df['TEAM_FTM']/df['TEAM_GP']
df['TEAM_FTA'] = df['TEAM_FTA']/df['TEAM_GP']
df['TEAM_OREB'] = df['TEAM_OREB']/df['TEAM_GP']
df['TEAM_DREB'] = df['TEAM_DREB']/df['TEAM_GP']
df['TEAM_REB'] = df['TEAM_REB']/df['TEAM_GP']
df['TEAM_AST'] = df['TEAM_AST']/df['TEAM_GP']
df['TEAM_STL'] = df['TEAM_STL']/df['TEAM_GP']
df['TEAM_BLK'] = df['TEAM_BLK']/df['TEAM_GP']
df['TEAM_BLKA'] = df['TEAM_BLKA']/df['TEAM_GP']
df['TEAM_TOV'] = df['TEAM_TOV']/df['TEAM_GP']
df['TEAM_PF'] = df['TEAM_PF']/df['TEAM_GP']
df['TEAM_PFD'] = df['TEAM_PFD']/df['TEAM_GP']
df['TEAM_PTS'] = df['TEAM_PTS']/df['TEAM_GP']
df['TEAM_PLUS_MINUS'] = df['TEAM_PLUS_MINUS']/df['TEAM_GP']

#OPPONENT
df['OPPONENT_MIN'] = df['OPPONENT_MIN']/df['OPPONENT_GP']
df['OPPONENT_FGM'] = df['OPPONENT_FGM']/df['OPPONENT_GP']
df['OPPONENT_FGA'] = df['OPPONENT_FGA']/df['OPPONENT_GP']
df['OPPONENT_FG3M'] = df['OPPONENT_FG3M']/df['OPPONENT_GP']
df['OPPONENT_FG3A'] = df['OPPONENT_FG3A']/df['OPPONENT_GP']
df['OPPONENT_FTM'] = df['OPPONENT_FTM']/df['OPPONENT_GP']
df['OPPONENT_FTA'] = df['OPPONENT_FTA']/df['OPPONENT_GP']
df['OPPONENT_OREB'] = df['OPPONENT_OREB']/df['OPPONENT_GP']
df['OPPONENT_DREB'] = df['OPPONENT_DREB']/df['OPPONENT_GP']
df['OPPONENT_REB'] = df['OPPONENT_REB']/df['OPPONENT_GP']
df['OPPONENT_AST'] = df['OPPONENT_AST']/df['OPPONENT_GP']
df['OPPONENT_TOV'] = df['OPPONENT_TOV']/df['OPPONENT_GP']
df['OPPONENT_STL'] = df['OPPONENT_STL']/df['OPPONENT_GP']
df['OPPONENT_BLK'] = df['OPPONENT_BLK']/df['OPPONENT_GP']
df['OPPONENT_BLKA'] = df['OPPONENT_BLKA']/df['OPPONENT_GP']
df['OPPONENT_PF'] = df['OPPONENT_PF']/df['OPPONENT_GP']
df['OPPONENT_PFD'] = df['OPPONENT_PFD']/df['OPPONENT_GP']
df['OPPONENT_PTS'] = df['OPPONENT_PTS']/df['OPPONENT_GP']
df['OPPONENT_PLUS_MINUS'] = df['OPPONENT_PLUS_MINUS']/df['OPPONENT_GP']

#against



season = df[['PLAYER_NAME','TEAM_CITY',"SEASON_SEASON_ID", 'SEASON_MIN','SEASON_FGM','SEASON_FGA', 'SEASON_FG3M','SEASON_FG3A','SEASON_FTM','SEASON_FTA','SEASON_OREB','SEASON_DREB','SEASON_REB','SEASON_AST','SEASON_STL','SEASON_BLK','SEASON_TOV','SEASON_PF','SEASON_PTS' ]] 

recent = df[['PLAYER_NAME','TEAM_CITY',"RECENT_MIN","RECENT_FGM","RECENT_FGA","RECENT_FG3M","RECENT_FG3A","RECENT_FTM","RECENT_FTA","RECENT_OREB","RECENT_DREB","RECENT_REB","RECENT_AST","RECENT_STL","RECENT_BLK","RECENT_TOV","RECENT_PF","RECENT_PTS", "RECENT_PLUS_MINUS"]]

team = df[['TEAM_CITY','PLAYER_NAME',"TEAM_MIN","TEAM_FGM","TEAM_FGA","TEAM_FG3M","TEAM_FG3A","TEAM_FTM","TEAM_FTA","TEAM_OREB","TEAM_DREB","TEAM_REB","TEAM_AST","TEAM_STL","TEAM_BLK","TEAM_TOV","TEAM_PF", 'TEAM_PFD',"TEAM_PTS","TEAM_PLUS_MINUS"]]

opponent = df[['PLAYER_NAME',"OPPONENT_MIN","OPPONENT_FGM","OPPONENT_FGA","OPPONENT_FG3M","OPPONENT_FG3A","OPPONENT_FTM","OPPONENT_FTA","OPPONENT_OREB","OPPONENT_DREB","OPPONENT_REB","OPPONENT_AST","OPPONENT_STL","OPPONENT_BLK","OPPONENT_TOV","OPPONENT_PF","OPPONENT_PFD","OPPONENT_PTS","OPPONENT_PLUS_MINUS"]]

against = df[['PLAYER_NAME',"AGAINT_OPP_MIN","AGAINT_OPP_FGM","AGAINT_OPP_FGA","AGAINT_OPP_FG3M","AGAINT_OPP_FG3A","AGAINT_OPP_FTM","AGAINT_OPP_FTA","AGAINT_OPP_OREB","AGAINT_OPP_DREB","AGAINT_OPP_REB","AGAINT_OPP_AST","AGAINT_OPP_STL","AGAINT_OPP_BLK","AGAINT_OPP_TOV","AGAINT_OPP_PF","AGAINT_OPP_PTS","AGAINT_OPP_PLUS_MINUS"]]

df = df[['GAME_ID','TEAM_CITY','PLAYER_NAME',"MIN","FGM","FGA","FG3M","FG3A","FTM","FTA","OREB","DREB","REB","AST","STL","BLK","TO","PF","PTS","PLUS_MINUS"]]



season.to_csv("season.csv", index=False)
recent.to_csv("recent.csv", index=False)
team.to_csv("team.csv", index=False)
opponent.to_csv("opponent.csv", index=False)
against.to_csv("fzagainst.csv", index=False)
df.to_csv("OUT.csv", index=False)